// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh32k-Ih3fV5wYZygxVULQdEdUGRyAZ9A',
    appId: '1:537144924449:web:3b6bc82dea5c6172dd8660',
    messagingSenderId: '537144924449',
    projectId: 'crop-disease-detection-33270',
    authDomain: 'crop-disease-detection-33270.firebaseapp.com',
    storageBucket: 'crop-disease-detection-33270.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaaxAsZnWBsvrXy1Z68CNQi1OLJ3QhXNI',
    appId: '1:537144924449:android:90e4d1574edca676dd8660',
    messagingSenderId: '537144924449',
    projectId: 'crop-disease-detection-33270',
    storageBucket: 'crop-disease-detection-33270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6pGZdN-nirfBZvVxv0RKa-xz7fnHYEs',
    appId: '1:537144924449:ios:3d6e75af1ea7d11ddd8660',
    messagingSenderId: '537144924449',
    projectId: 'crop-disease-detection-33270',
    storageBucket: 'crop-disease-detection-33270.appspot.com',
    iosBundleId: 'com.example.cropDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa6pGZdN-nirfBZvVxv0RKa-xz7fnHYEs',
    appId: '1:537144924449:ios:6c530bc56ee359fedd8660',
    messagingSenderId: '537144924449',
    projectId: 'crop-disease-detection-33270',
    storageBucket: 'crop-disease-detection-33270.appspot.com',
    iosBundleId: 'com.example.cropDiseaseDetection.RunnerTests',
  );
}
